# Generated by Django 3.0.6 on 2020-05-17 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
        ('account', '0002_auto_20200515_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='vcs.Repository'),
        ),
    ]
