# Generated by Django 3.0.6 on 2020-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='link',
            new_name='url',
        ),
    ]
